/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import data.Juego;
import data.Jugador;
import data.Personaje;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
/**
 *
 * @author beto arias
 */
public class Game extends javax.swing.JFrame {
Juego constructor = new Juego();
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        historia = new javax.swing.JTextField();
        monstruos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtA_Historia = new javax.swing.JTextArea();
        bt_EDIT1 = new javax.swing.JButton();
        Btn_Add = new javax.swing.JButton();
        Btn_See = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        vitacora = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtA_Vitacora = new javax.swing.JTextArea();
        Btn_Vitacora = new javax.swing.JButton();
        Btn_Maps = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        NPC1 = new javax.swing.JButton();
        NPC2 = new javax.swing.JButton();
        NPC3 = new javax.swing.JButton();
        NPC4 = new javax.swing.JButton();
        jugador1 = new javax.swing.JButton();
        jugador2 = new javax.swing.JButton();
        jugador3 = new javax.swing.JButton();
        jugador4 = new javax.swing.JButton();
        jugador5 = new javax.swing.JButton();
        jugador6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        monstruosList = new javax.swing.JList<>();
        nombreUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroJugadores = new javax.swing.JLabel();
        nombreJuego = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        historia.setText("historia:");
        historia.setEnabled(false);
        historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaActionPerformed(evt);
            }
        });

        monstruos.setText("monstruos:");
        monstruos.setEnabled(false);

        TxtA_Historia.setColumns(20);
        TxtA_Historia.setRows(5);
        jScrollPane2.setViewportView(TxtA_Historia);

        bt_EDIT1.setText("EDITAR");

        Btn_Add.setText("AGREGAR");

        Btn_See.setText("VER");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        vitacora.setText("vitacora:");
        vitacora.setEnabled(false);

        TxtA_Vitacora.setColumns(20);
        TxtA_Vitacora.setRows(5);
        jScrollPane3.setViewportView(TxtA_Vitacora);

        Btn_Vitacora.setText("Agregar Bitacora");

        Btn_Maps.setText("Mapas");

        jLabel1.setText("NPC");

        NPC1.setText("NPC 1");
        NPC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPC1ActionPerformed(evt);
            }
        });

        NPC2.setText("NPC 2");
        NPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPC2ActionPerformed(evt);
            }
        });

        NPC3.setText("NPC 3");
        NPC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPC3ActionPerformed(evt);
            }
        });

        NPC4.setText("NPC 4");
        NPC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPC4ActionPerformed(evt);
            }
        });

        jugador1.setText("jugador1");
        jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador1ActionPerformed(evt);
            }
        });

        jugador2.setText("jugador2");
        jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador2ActionPerformed(evt);
            }
        });

        jugador3.setText("jugador3");
        jugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador3ActionPerformed(evt);
            }
        });

        jugador4.setText("jugador4");
        jugador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador4ActionPerformed(evt);
            }
        });

        jugador5.setText("jugador5");
        jugador5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador5ActionPerformed(evt);
            }
        });

        jugador6.setText("jugador6");
        jugador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador6ActionPerformed(evt);
            }
        });

        monstruosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "monstruo 1", "monstruo 2", "monstruo 3", "monstruo 4", "monstruo 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(monstruosList);

        jLabel2.setText("numero de jugadores:");

        itemsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(itemsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NPC1)
                                .addGap(26, 26, 26)
                                .addComponent(NPC2)
                                .addGap(29, 29, 29)
                                .addComponent(NPC3)
                                .addGap(33, 33, 33)
                                .addComponent(NPC4)))
                        .addGap(104, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Maps)
                            .addComponent(Btn_Vitacora))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(historia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt_EDIT1))
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Btn_Add)
                                                .addGap(18, 18, 18)
                                                .addComponent(Btn_See))
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(monstruos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jugador1)
                                .addComponent(jugador2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jugador3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jugador4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jugador5)
                    .addComponent(jugador6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monstruos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vitacora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_EDIT1))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Btn_Add)
                                            .addComponent(Btn_See)))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugador1)
                                .addGap(18, 18, 18)
                                .addComponent(jugador2)
                                .addGap(18, 18, 18)
                                .addComponent(jugador3)
                                .addGap(18, 18, 18)
                                .addComponent(jugador4)
                                .addGap(18, 18, 18)
                                .addComponent(jugador5)
                                .addGap(18, 18, 18)
                                .addComponent(jugador6)
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Vitacora)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NPC1)
                    .addComponent(NPC2)
                    .addComponent(NPC3)
                    .addComponent(NPC4)
                    .addComponent(Btn_Maps))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historiaActionPerformed

    private void jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador1ActionPerformed
       if(jugador1.getText()!= null){
            String[] nombrePersonaje= new String[5];
            nombrePersonaje[0]= jugador1.getText();
            Personaje[] personaje = new Personaje[5];
            Jugador  aux = new Jugador();
       
       personaje  = aux.listaDeObjetosPersonaje(nombrePersonaje) ;
       JOptionPane.showMessageDialog(rootPane, personaje[0].toString());
       }
       
    }//GEN-LAST:event_jugador1ActionPerformed

    private void jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador2ActionPerformed
       if(jugador2.getText()!= null){
            String[] nombrePersonaje= new String[5];
            nombrePersonaje[0]= jugador2.getText();
            Personaje[] personaje = new Personaje[5];
            Jugador  aux = new Jugador();
       
       personaje  = aux.listaDeObjetosPersonaje(nombrePersonaje) ;
       JOptionPane.showMessageDialog(rootPane, personaje[0].toString());
       }
    }//GEN-LAST:event_jugador2ActionPerformed

    private void jugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador3ActionPerformed
       if(jugador3.getText()!= null){
            String[] nombrePersonaje= new String[5];
            nombrePersonaje[0]= jugador3.getText();
            Personaje[] personaje = new Personaje[5];
            Jugador  aux = new Jugador();
       
       personaje  = aux.listaDeObjetosPersonaje(nombrePersonaje) ;
       JOptionPane.showMessageDialog(rootPane, personaje[0].toString());
       }
    }//GEN-LAST:event_jugador3ActionPerformed

    private void jugador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador4ActionPerformed
       if(jugador4.getText()!= null){
            String[] nombrePersonaje= new String[5];
            nombrePersonaje[0]= jugador4.getText();
            Personaje[] personaje = new Personaje[5];
            Jugador  aux = new Jugador();
       
       personaje  = aux.listaDeObjetosPersonaje(nombrePersonaje) ;
       JOptionPane.showMessageDialog(rootPane, personaje[0].toString());
       }
    }//GEN-LAST:event_jugador4ActionPerformed

    private void jugador5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador5ActionPerformed
       if(jugador5.getText()!= null){
            String[] nombrePersonaje= new String[5];
            nombrePersonaje[0]= jugador5.getText();
            Personaje[] personaje = new Personaje[5];
            Jugador  aux = new Jugador();
       
       personaje  = aux.listaDeObjetosPersonaje(nombrePersonaje) ;
       JOptionPane.showMessageDialog(rootPane, personaje[0].toString());
       }
    }//GEN-LAST:event_jugador5ActionPerformed

    private void jugador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador6ActionPerformed
       if(jugador6.getText()!= null){
            String[] nombrePersonaje= new String[5];
            nombrePersonaje[0]= jugador6.getText();
            Personaje[] personaje = new Personaje[5];
            Jugador  aux = new Jugador();
       
       personaje  = aux.listaDeObjetosPersonaje(nombrePersonaje) ;
       JOptionPane.showMessageDialog(rootPane, personaje[0].toString());
       }
    }//GEN-LAST:event_jugador6ActionPerformed

    
    
    
    private void NPC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPC1ActionPerformed
        if(NPC1.getText()!= null){
       Personaje npc = new Personaje();
       JOptionPane.showMessageDialog(rootPane, npc.leerObjetoPersonaje(NPC1.getText()).toString());
       }
    }//GEN-LAST:event_NPC1ActionPerformed

    private void NPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPC2ActionPerformed
         if(NPC2.getText()!= null){
       Personaje npc = new Personaje();
       JOptionPane.showMessageDialog(rootPane, npc.leerObjetoPersonaje(NPC2.getText()).toString());
       }
    }//GEN-LAST:event_NPC2ActionPerformed

    private void NPC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPC3ActionPerformed
         if(NPC3.getText()!= null){
       Personaje npc = new Personaje();
       JOptionPane.showMessageDialog(rootPane, npc.leerObjetoPersonaje(NPC3.getText()).toString());
       }
    }//GEN-LAST:event_NPC3ActionPerformed

    private void NPC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPC4ActionPerformed
         if(NPC4.getText()!= null){
       Personaje npc = new Personaje();
       JOptionPane.showMessageDialog(rootPane, npc.leerObjetoPersonaje(NPC4.getText()).toString());
       }
    }//GEN-LAST:event_NPC4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Add;
    private javax.swing.JButton Btn_Maps;
    private javax.swing.JButton Btn_See;
    private javax.swing.JButton Btn_Vitacora;
    private javax.swing.JButton NPC1;
    private javax.swing.JButton NPC2;
    private javax.swing.JButton NPC3;
    private javax.swing.JButton NPC4;
    private javax.swing.JTextArea TxtA_Historia;
    private javax.swing.JTextArea TxtA_Vitacora;
    private javax.swing.JButton bt_EDIT1;
    private javax.swing.JTextField historia;
    private javax.swing.JList<String> itemsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jugador1;
    private javax.swing.JButton jugador2;
    private javax.swing.JButton jugador3;
    private javax.swing.JButton jugador4;
    private javax.swing.JButton jugador5;
    private javax.swing.JButton jugador6;
    private javax.swing.JTextField monstruos;
    private javax.swing.JList<String> monstruosList;
    private javax.swing.JLabel nombreJuego;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JLabel numeroJugadores;
    private javax.swing.JTextField vitacora;
    // End of variables declaration//GEN-END:variables

    public JLabel getNombreJuego() {
        return nombreJuego;
    }

    public void setNombreJuego(String texto) {
        nombreJuego.setText(texto);
    }

    public JLabel getNombreUsuario() {
        return nombreUsuario;
    }

    public void setNombreUsuario(String texto) {
        nombreUsuario.setText(texto);
    }

    public JLabel getNumeroJugadores() {
        return numeroJugadores;
    }

    public void setNumeroJugadores(String texto) {
        numeroJugadores.setText(texto);
    }

    
    
    public JTextArea getTxtA_Historia() {
        return TxtA_Historia;
    }

    public void setTxtA_Historia(String texto) {
        TxtA_Historia.setText(texto);
    }

    public JTextArea getTxtA_Vitacora() {
        return TxtA_Vitacora;
    }

    public void setTxtA_Vitacora(String texto) {
        TxtA_Vitacora.setText(texto);
    }

    public JList<String> getItemsList() {
        return monstruosList;
    }

    public void setItemsList(String [] texto) {
        
        monstruosList.setListData(texto);
    }

    public JList<String> getMonstruosList() {
        return monstruosList;
    }

    public void setMonstruosList(String [] texto) {
         monstruosList.setListData(texto);
    }

    
    
    
    public JButton getJugador1() {
        return jugador1;
    }

    public void setJugador1(String texto) {
        jugador1.setText(texto);;
    }

    public JButton getJugador2() {
        return jugador2;
    }

    public void setJugador2(String texto) {
        jugador2.setText(texto);
    }

    public JButton getJugador3() {
        return jugador3;
    }

    public void setJugador3(String texto) {
       jugador3.setText(texto);
    }

    public JButton getJugador4() {
        return jugador4;
    }

    public void setJugador4(String texto) {
        jugador4.setText(texto);
    }

    public JButton getJugador5() {
        return jugador5;
    }

    public void setJugador5(String texto) {
        jugador5.setText(texto);
    }

    public JButton getJugador6() {
        return jugador6;
    }

    public void setJugador6(String texto) {
        jugador6.setText(texto);
    }

    public JButton getNPC1() {
        return NPC1;
    }

    public void setNPC1(String texto) {
        NPC1.setText(texto);
    }

    public JButton getNPC2() {
        return NPC2;
    }

    public void setNPC2(String texto) {
         NPC2.setText(texto);
    }

    public JButton getNPC3() {
        return NPC3;
    }

    public void setNPC3(String texto) {
        NPC3.setText(texto);
    }

    public JButton getNPC4() {
        return NPC4;
    }

    public void setNPC4(String texto) {
        NPC4.setText(texto);
    }

    public Juego getConstructor() {
        return constructor;
    }

    public void setConstructor(Juego constructor) {
        this.constructor = constructor;
    }

    
    
    
}
